// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	"strings"

	"github.com/atom-apps/door/common"
	"github.com/atom-apps/door/modules/users/controller"
	"github.com/atom-apps/door/modules/users/dto"
	"github.com/atom-providers/jwt"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeUserController(engine fiber.Router, controller *controller.UserController) {
	basePath := "/" + engine.(*fiber.Group).Prefix
	engine.Get(strings.TrimPrefix("/v1/users/profile", basePath), DataFunc1(controller.Profile, JwtClaim[jwt.Claims](ClaimParamError)))
	engine.Get(strings.TrimPrefix("/v1/users/:id<int>", basePath), DataFunc1(controller.Show, Integer[int64]("id", PathParamError)))
	engine.Get(strings.TrimPrefix("/v1/users", basePath), DataFunc3(controller.List, Query[dto.UserListQueryFilter](QueryParamError), Query[common.PageQueryFilter](QueryParamError), Query[common.SortQueryFilter](QueryParamError)))
	engine.Post(strings.TrimPrefix("/v1/users", basePath), Func1(controller.Create, Body[dto.UserForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/v1/users/:id<int>", basePath), Func2(controller.Update, Integer[int64]("id", PathParamError), Body[dto.UserForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/v1/users/:id<int>", basePath), Func1(controller.Delete, Integer[int64]("id", PathParamError)))
}
