// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	"strings"

	"github.com/atom-apps/door/modules/service/controller"
	"github.com/atom-apps/door/modules/service/dto"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeSendController(engine fiber.Router, controller *controller.SendController) {
	basePath := "/" + engine.(*fiber.Group).Prefix
	engine.Post(strings.TrimPrefix("/services/send/sms", basePath), Func1(controller.Sms, Body[dto.SendVerifyCodeForm](BodyParamError)))
	engine.Post(strings.TrimPrefix("/services/send/email", basePath), Func1(controller.Email, Body[dto.SendVerifyCodeForm](BodyParamError)))
}
