// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	"strings"

	"github.com/atom-apps/door/modules/auth/controller"
	"github.com/atom-providers/jwt"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeRoutesController(engine fiber.Router, controller *controller.RoutesController) {
	groupPrefix := "/" + strings.TrimLeft(engine.(*fiber.Group).Prefix, "/")
	engine.Get(strings.TrimPrefix("/v1/auth/routes", groupPrefix), DataFunc(controller.List))
	engine.Get(strings.TrimPrefix("/v1/auth/pages", groupPrefix), DataFunc1(controller.Pages, JwtClaim[jwt.Claims](ClaimParamError)))
	engine.Get(strings.TrimPrefix("/v1/auth/test", groupPrefix), DataFunc(controller.Test))
}
