// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	"strings"

	"github.com/atom-apps/door/modules/auth/controller"
	"github.com/atom-apps/door/modules/auth/dto"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routePermissionController(engine fiber.Router, controller *controller.PermissionController) {
	basePath := "/" + engine.(*fiber.Group).Prefix
	engine.Post(strings.TrimPrefix("/v1/permission/check", basePath), Func1(controller.Check, Body[dto.PermissionCheckForm](BodyParamError)))
}
