// Code generated by go-enum DO NOT EDIT.
// Version: -
// Revision: -
// Build Date: -
// Built By: -

package consts

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// CacheKeyRegisterCode is a CacheKey of type RegisterCode.
	CacheKeyRegisterCode CacheKey = "code:register:%s"
)

var ErrInvalidCacheKey = fmt.Errorf("not a valid CacheKey, try [%s]", strings.Join(_CacheKeyNames, ", "))

var _CacheKeyNames = []string{
	string(CacheKeyRegisterCode),
}

// CacheKeyNames returns a list of possible string values of CacheKey.
func CacheKeyNames() []string {
	tmp := make([]string, len(_CacheKeyNames))
	copy(tmp, _CacheKeyNames)
	return tmp
}

// CacheKeyValues returns a list of the values for CacheKey
func CacheKeyValues() []CacheKey {
	return []CacheKey{
		CacheKeyRegisterCode,
	}
}

// String implements the Stringer interface.
func (x CacheKey) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CacheKey) IsValid() bool {
	_, err := ParseCacheKey(string(x))
	return err == nil
}

var _CacheKeyValue = map[string]CacheKey{
	"code:register:%s": CacheKeyRegisterCode,
}

// ParseCacheKey attempts to convert a string to a CacheKey.
func ParseCacheKey(name string) (CacheKey, error) {
	if x, ok := _CacheKeyValue[name]; ok {
		return x, nil
	}
	return CacheKey(""), fmt.Errorf("%s is %w", name, ErrInvalidCacheKey)
}

var errCacheKeyNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *CacheKey) Scan(value interface{}) (err error) {
	if value == nil {
		*x = CacheKey("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseCacheKey(v)
	case []byte:
		*x, err = ParseCacheKey(string(v))
	case CacheKey:
		*x = v
	case *CacheKey:
		if v == nil {
			return errCacheKeyNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errCacheKeyNilPtr
		}
		*x, err = ParseCacheKey(*v)
	default:
		return errors.New("invalid type for CacheKey")
	}

	return
}

// Value implements the driver Valuer interface.
func (x CacheKey) Value() (driver.Value, error) {
	return x.String(), nil
}

// Set implements the Golang flag.Value interface func.
func (x *CacheKey) Set(val string) error {
	v, err := ParseCacheKey(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *CacheKey) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *CacheKey) Type() string {
	return "CacheKey"
}

type NullCacheKey struct {
	CacheKey CacheKey
	Valid    bool
}

func NewNullCacheKey(val interface{}) (x NullCacheKey) {
	err := x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	_ = err            // make any errcheck linters happy
	return
}

// Scan implements the Scanner interface.
func (x *NullCacheKey) Scan(value interface{}) (err error) {
	if value == nil {
		x.CacheKey, x.Valid = CacheKey(""), false
		return
	}

	err = x.CacheKey.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullCacheKey) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	// driver.Value accepts int64 for int values.
	return string(x.CacheKey), nil
}

type NullCacheKeyStr struct {
	NullCacheKey
}

func NewNullCacheKeyStr(val interface{}) (x NullCacheKeyStr) {
	x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	return
}

// Value implements the driver Valuer interface.
func (x NullCacheKeyStr) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.CacheKey.String(), nil
}
