// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/door/modules/systems/controller"
	"github.com/atom-apps/door/modules/systems/dto"
	"github.com/atom-apps/door/common"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeRouteController(engine fiber.Router, controller *controller.RouteController) {
	basePath := "/"+engine.(*fiber.Group).Prefix
	engine.Get(strings.TrimPrefix("/v1/routes/:id<int>", basePath), DataFunc1(controller.Show, Integer[int64]("id", PathParamError)))
	engine.Get(strings.TrimPrefix("/v1/routes", basePath), DataFunc3(controller.List, Query[dto.RouteListQueryFilter](QueryParamError), Query[common.PageQueryFilter](QueryParamError), Query[common.SortQueryFilter](QueryParamError)))
	engine.Get(strings.TrimPrefix("/v1/routes/pages/:mode", basePath), DataFunc1(controller.Pages, String("mode", PathParamError)))
	engine.Post(strings.TrimPrefix("/v1/routes", basePath), Func1(controller.Create, Body[dto.RouteForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/v1/routes/:id<int>", basePath), Func2(controller.Update, Integer[int64]("id", PathParamError), Body[dto.RouteForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/v1/routes/:id<int>", basePath), Func1(controller.Delete, Integer[int64]("id", PathParamError)))
}
