// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm/schema"
)

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Code     int64  `gorm:"column:code;type:bigint;comment:行政区划代码" json:"code"` // 行政区划代码
	Name     string `gorm:"column:name;type:text" json:"name"`
	Province string `gorm:"column:province;type:text" json:"province"`
	City     string `gorm:"column:city;type:text" json:"city"`
	Area     string `gorm:"column:area;type:text" json:"area"`
	Town     string `gorm:"column:town;type:text" json:"town"`
}

func (*Location) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameLocation
	}
	return namer.TableName(TableNameLocation)
}
