// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm/schema"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID          int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;type:character varying(128)" json:"name"`
	Slug        string `gorm:"column:slug;type:character varying(128)" json:"slug"`
	Description string `gorm:"column:description;type:character varying(256)" json:"description"`
	ParentID    int64  `gorm:"column:parent_id;type:bigint" json:"parent_id"`
}

func (*Role) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameRole
	}
	return namer.TableName(TableNameRole)
}
