// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm/schema"
)

const TableNameRoleUser = "role_users"

// RoleUser mapped from table <role_users>
type RoleUser struct {
	ID       int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	RoleID   int64 `gorm:"column:role_id;type:bigint" json:"role_id"`
	UserID   int64 `gorm:"column:user_id;type:bigint" json:"user_id"`
	TenantID int64 `gorm:"column:tenant_id;type:bigint" json:"tenant_id"`
}

func (*RoleUser) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameRoleUser
	}
	return namer.TableName(TableNameRoleUser)
}
