// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm/schema"
)

const TableNameUserTenantRole = "user_tenant_roles"

// UserTenantRole mapped from table <user_tenant_roles>
type UserTenantRole struct {
	ID        uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	CreatedAt time.Time `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                 // 创建时间
	UserID    uint64    `gorm:"column:user_id;type:bigint unsigned;not null;comment:用户ID" json:"user_id"`          // 用户ID
	TenantID  uint64    `gorm:"column:tenant_id;type:bigint unsigned;not null;comment:租户ID" json:"tenant_id"`      // 租户ID
	RoleID    uint64    `gorm:"column:role_id;type:bigint unsigned;not null;comment:角色ID" json:"role_id"`          // 角色ID
}

func (*UserTenantRole) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameUserTenantRole
	}
	return namer.TableName(TableNameUserTenantRole)
}
