// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

const TableNameUserAddress = "user_addresses"

// UserAddress mapped from table <user_addresses>
type UserAddress struct {
	ID        uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"`  // ID
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);comment:创建时间" json:"created_at"`                      // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);comment:更新时间" json:"updated_at"`                      // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);comment:删除时间" json:"deleted_at" swaggertype:"string"` // 删除时间
	UserID    uint64         `gorm:"column:user_id;type:bigint(20) unsigned;comment:用户ID" json:"user_id"`                    // 用户ID
	Code      string         `gorm:"column:code;type:varchar(6);comment:行政区划代码" json:"code"`                                 // 行政区划代码
	Town      string         `gorm:"column:town;type:varchar(6);comment:街道" json:"town"`                                     // 街道
	Detail    string         `gorm:"column:detail;type:varchar(256);comment:详细地址" json:"detail"`                             // 详细地址
	Name      string         `gorm:"column:name;type:varchar(64);comment:姓名" json:"name"`                                    // 姓名
	Phone     string         `gorm:"column:phone;type:varchar(24);comment:联系电话" json:"phone"`                                // 联系电话
	ZipCode   string         `gorm:"column:zip_code;type:varchar(12);comment:邮编" json:"zip_code"`                            // 邮编
	IsDefault bool           `gorm:"column:is_default;type:tinyint(1);comment:默认地址" json:"is_default"`                       // 默认地址
}

func (*UserAddress) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameUserAddress
	}
	return namer.TableName(TableNameUserAddress)
}
