// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/door/modules/tools/controller"
	"github.com/atom-providers/jwt"
	"github.com/atom-apps/door/modules/tools/dto"
	"github.com/atom-apps/door/common"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeLocationController(engine fiber.Router, controller *controller.LocationController) {
	basePath := "/"+engine.(*fiber.Group).Prefix
	engine.Get(strings.TrimPrefix("/v1/tools/locations/:id<int>", basePath), DataFunc2(controller.Show, JwtClaim[jwt.Claims](ClaimParamError), Integer[uint64]("id", PathParamError)))
	engine.Get(strings.TrimPrefix("/v1/tools/locations", basePath), DataFunc4(controller.List, JwtClaim[jwt.Claims](ClaimParamError), Query[dto.LocationListQueryFilter](QueryParamError), Query[common.PageQueryFilter](QueryParamError), Query[common.SortQueryFilter](QueryParamError)))
	engine.Post(strings.TrimPrefix("/v1/tools/locations", basePath), Func2(controller.Create, JwtClaim[jwt.Claims](ClaimParamError), Body[dto.LocationForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/v1/tools/locations/:id<int>", basePath), Func3(controller.Update, JwtClaim[jwt.Claims](ClaimParamError), Integer[uint64]("id", PathParamError), Body[dto.LocationForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/v1/tools/locations/:id<int>", basePath), Func2(controller.Delete, JwtClaim[jwt.Claims](ClaimParamError), Integer[uint64]("id", PathParamError)))
}
