// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/atom-apps/door/database/models"
)

func newDictionary(db *gorm.DB, opts ...gen.DOOption) dictionary {
	_dictionary := dictionary{}

	_dictionary.dictionaryDo.UseDB(db, opts...)
	_dictionary.dictionaryDo.UseModel(&models.Dictionary{})

	tableName := _dictionary.dictionaryDo.TableName()
	_dictionary.ALL = field.NewAsterisk(tableName)
	_dictionary.ID = field.NewUint64(tableName, "id")
	_dictionary.CreatedAt = field.NewTime(tableName, "created_at")
	_dictionary.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dictionary.DeletedAt = field.NewField(tableName, "deleted_at")
	_dictionary.Name = field.NewString(tableName, "name")
	_dictionary.Slug = field.NewString(tableName, "slug")
	_dictionary.Description = field.NewString(tableName, "description")
	_dictionary.Items = field.NewField(tableName, "items")

	_dictionary.fillFieldMap()

	return _dictionary
}

type dictionary struct {
	dictionaryDo dictionaryDo

	ALL         field.Asterisk
	ID          field.Uint64 // ID
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 删除时间
	Name        field.String // 名称
	Slug        field.String // 别名
	Description field.String // 描述
	Items       field.Field  // 选项

	fieldMap map[string]field.Expr
}

func (d dictionary) Table(newTableName string) *dictionary {
	d.dictionaryDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dictionary) As(alias string) *dictionary {
	d.dictionaryDo.DO = *(d.dictionaryDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dictionary) updateTableName(table string) *dictionary {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint64(table, "id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewField(table, "deleted_at")
	d.Name = field.NewString(table, "name")
	d.Slug = field.NewString(table, "slug")
	d.Description = field.NewString(table, "description")
	d.Items = field.NewField(table, "items")

	d.fillFieldMap()

	return d
}

func (d *dictionary) WithContext(ctx context.Context) IDictionaryDo {
	return d.dictionaryDo.WithContext(ctx)
}

func (d dictionary) TableName() string { return d.dictionaryDo.TableName() }

func (d dictionary) Alias() string { return d.dictionaryDo.Alias() }

func (d dictionary) Columns(cols ...field.Expr) gen.Columns { return d.dictionaryDo.Columns(cols...) }

func (d *dictionary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dictionary) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
	d.fieldMap["name"] = d.Name
	d.fieldMap["slug"] = d.Slug
	d.fieldMap["description"] = d.Description
	d.fieldMap["items"] = d.Items
}

func (d dictionary) clone(db *gorm.DB) dictionary {
	d.dictionaryDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dictionary) replaceDB(db *gorm.DB) dictionary {
	d.dictionaryDo.ReplaceDB(db)
	return d
}

type dictionaryDo struct{ gen.DO }

type IDictionaryDo interface {
	gen.SubQuery
	Debug() IDictionaryDo
	WithContext(ctx context.Context) IDictionaryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDictionaryDo
	WriteDB() IDictionaryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDictionaryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDictionaryDo
	Not(conds ...gen.Condition) IDictionaryDo
	Or(conds ...gen.Condition) IDictionaryDo
	Select(conds ...field.Expr) IDictionaryDo
	Where(conds ...gen.Condition) IDictionaryDo
	Order(conds ...field.Expr) IDictionaryDo
	Distinct(cols ...field.Expr) IDictionaryDo
	Omit(cols ...field.Expr) IDictionaryDo
	Join(table schema.Tabler, on ...field.Expr) IDictionaryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryDo
	Group(cols ...field.Expr) IDictionaryDo
	Having(conds ...gen.Condition) IDictionaryDo
	Limit(limit int) IDictionaryDo
	Offset(offset int) IDictionaryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryDo
	Unscoped() IDictionaryDo
	Create(values ...*models.Dictionary) error
	CreateInBatches(values []*models.Dictionary, batchSize int) error
	Save(values ...*models.Dictionary) error
	First() (*models.Dictionary, error)
	Take() (*models.Dictionary, error)
	Last() (*models.Dictionary, error)
	Find() ([]*models.Dictionary, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Dictionary, err error)
	FindInBatches(result *[]*models.Dictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Dictionary) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDictionaryDo
	Assign(attrs ...field.AssignExpr) IDictionaryDo
	Joins(fields ...field.RelationField) IDictionaryDo
	Preload(fields ...field.RelationField) IDictionaryDo
	FirstOrInit() (*models.Dictionary, error)
	FirstOrCreate() (*models.Dictionary, error)
	FindByPage(offset int, limit int) (result []*models.Dictionary, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDictionaryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dictionaryDo) Debug() IDictionaryDo {
	return d.withDO(d.DO.Debug())
}

func (d dictionaryDo) WithContext(ctx context.Context) IDictionaryDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dictionaryDo) ReadDB() IDictionaryDo {
	return d.Clauses(dbresolver.Read)
}

func (d dictionaryDo) WriteDB() IDictionaryDo {
	return d.Clauses(dbresolver.Write)
}

func (d dictionaryDo) Session(config *gorm.Session) IDictionaryDo {
	return d.withDO(d.DO.Session(config))
}

func (d dictionaryDo) Clauses(conds ...clause.Expression) IDictionaryDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dictionaryDo) Returning(value interface{}, columns ...string) IDictionaryDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dictionaryDo) Not(conds ...gen.Condition) IDictionaryDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dictionaryDo) Or(conds ...gen.Condition) IDictionaryDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dictionaryDo) Select(conds ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dictionaryDo) Where(conds ...gen.Condition) IDictionaryDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dictionaryDo) Order(conds ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dictionaryDo) Distinct(cols ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dictionaryDo) Omit(cols ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dictionaryDo) Join(table schema.Tabler, on ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dictionaryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dictionaryDo) RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dictionaryDo) Group(cols ...field.Expr) IDictionaryDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dictionaryDo) Having(conds ...gen.Condition) IDictionaryDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dictionaryDo) Limit(limit int) IDictionaryDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dictionaryDo) Offset(offset int) IDictionaryDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dictionaryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dictionaryDo) Unscoped() IDictionaryDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dictionaryDo) Create(values ...*models.Dictionary) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dictionaryDo) CreateInBatches(values []*models.Dictionary, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dictionaryDo) Save(values ...*models.Dictionary) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dictionaryDo) First() (*models.Dictionary, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Dictionary), nil
	}
}

func (d dictionaryDo) Take() (*models.Dictionary, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Dictionary), nil
	}
}

func (d dictionaryDo) Last() (*models.Dictionary, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Dictionary), nil
	}
}

func (d dictionaryDo) Find() ([]*models.Dictionary, error) {
	result, err := d.DO.Find()
	return result.([]*models.Dictionary), err
}

func (d dictionaryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Dictionary, err error) {
	buf := make([]*models.Dictionary, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dictionaryDo) FindInBatches(result *[]*models.Dictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dictionaryDo) Attrs(attrs ...field.AssignExpr) IDictionaryDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dictionaryDo) Assign(attrs ...field.AssignExpr) IDictionaryDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dictionaryDo) Joins(fields ...field.RelationField) IDictionaryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dictionaryDo) Preload(fields ...field.RelationField) IDictionaryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dictionaryDo) FirstOrInit() (*models.Dictionary, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Dictionary), nil
	}
}

func (d dictionaryDo) FirstOrCreate() (*models.Dictionary, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Dictionary), nil
	}
}

func (d dictionaryDo) FindByPage(offset int, limit int) (result []*models.Dictionary, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dictionaryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dictionaryDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dictionaryDo) Delete(models ...*models.Dictionary) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dictionaryDo) withDO(do gen.Dao) *dictionaryDo {
	d.DO = *do.(*gen.DO)
	return d
}
