// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	Migration      *migration
	PermissionRule *permissionRule
	Session        *session
	Tenant         *tenant
	TenantUser     *tenantUser
	Token          *token
	User           *user
	UserInfo       *userInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Migration = &Q.Migration
	PermissionRule = &Q.PermissionRule
	Session = &Q.Session
	Tenant = &Q.Tenant
	TenantUser = &Q.TenantUser
	Token = &Q.Token
	User = &Q.User
	UserInfo = &Q.UserInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Migration:      newMigration(db, opts...),
		PermissionRule: newPermissionRule(db, opts...),
		Session:        newSession(db, opts...),
		Tenant:         newTenant(db, opts...),
		TenantUser:     newTenantUser(db, opts...),
		Token:          newToken(db, opts...),
		User:           newUser(db, opts...),
		UserInfo:       newUserInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Migration      migration
	PermissionRule permissionRule
	Session        session
	Tenant         tenant
	TenantUser     tenantUser
	Token          token
	User           user
	UserInfo       userInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Migration:      q.Migration.clone(db),
		PermissionRule: q.PermissionRule.clone(db),
		Session:        q.Session.clone(db),
		Tenant:         q.Tenant.clone(db),
		TenantUser:     q.TenantUser.clone(db),
		Token:          q.Token.clone(db),
		User:           q.User.clone(db),
		UserInfo:       q.UserInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Migration:      q.Migration.replaceDB(db),
		PermissionRule: q.PermissionRule.replaceDB(db),
		Session:        q.Session.replaceDB(db),
		Tenant:         q.Tenant.replaceDB(db),
		TenantUser:     q.TenantUser.replaceDB(db),
		Token:          q.Token.replaceDB(db),
		User:           q.User.replaceDB(db),
		UserInfo:       q.UserInfo.replaceDB(db),
	}
}

type queryCtx struct {
	Migration      IMigrationDo
	PermissionRule IPermissionRuleDo
	Session        ISessionDo
	Tenant         ITenantDo
	TenantUser     ITenantUserDo
	Token          ITokenDo
	User           IUserDo
	UserInfo       IUserInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Migration:      q.Migration.WithContext(ctx),
		PermissionRule: q.PermissionRule.WithContext(ctx),
		Session:        q.Session.WithContext(ctx),
		Tenant:         q.Tenant.WithContext(ctx),
		TenantUser:     q.TenantUser.WithContext(ctx),
		Token:          q.Token.WithContext(ctx),
		User:           q.User.WithContext(ctx),
		UserInfo:       q.UserInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
