// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm/schema"
)

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
	UserID    int64     `gorm:"column:user_id;type:bigint" json:"user_id"`
	SessionID string    `gorm:"column:session_id;type:character varying(64)" json:"session_id"`
	ExpireAt  time.Time `gorm:"column:expire_at;type:timestamp with time zone" json:"expire_at"`
}

func (*Session) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameSession
	}
	return namer.TableName(TableNameSession)
}
